### ISSUE TITLE
Command 'Extract to Component file' resulted in an error (command 'extension.react-refactor.extractToFile' not found)

### ISSUE THREAD

**Issue by roninbar** [planbcoding/vscode-react-refactor#11]
I'm getting this error when I try to use the extension.
Plus, I don't see the additional commands in the light bulb menu.
I tried to uninstall and reinstall the extension but it didn't help.

**Comment by c01nd01r** [comment]
I don't get any errors, but instead of creating file, `Extract to Component file` command create class component in current file.
<details>
  <summary>Screenshots</summary>
  
![Снимок экрана 2020-09-28 в 15 41 49](https://user-images.githubusercontent.com/3511312/94441897-fb2d0880-01ab-11eb-879c-fc4580590b06.png)
![Снимок экрана 2020-09-28 в 15 42 18](https://user-images.githubusercontent.com/3511312/94441927-02541680-01ac-11eb-81e6-ef1b882edff2.png)


</details>

**Comment by ghost1face** [comment]
I just installed this and get the same error:

![image](https://user-images.githubusercontent.com/2773690/95132926-81a69480-072e-11eb-872b-dbf5ae8c39fe.png)

Here's my VSCode version info:

![image](https://user-images.githubusercontent.com/2773690/95132892-75bad280-072e-11eb-9850-e7742fd8ea99.png)

**Comment by tino-brst** [comment]
> I don't get any errors, but instead of creating file, `Extract to Component file` command create class component in current file.
> 
> Screenshots
> ![Снимок экрана 2020-09-28 в 15 41 49](https://user-images.githubusercontent.com/3511312/94441897-fb2d0880-01ab-11eb-879c-fc4580590b06.png)
> ![Снимок экрана 2020-09-28 в 15 42 18](https://user-images.githubusercontent.com/3511312/94441927-02541680-01ac-11eb-81e6-ef1b882edff2.png)

Yep, same here (awesome extension btw! 🙌)

**Comment by andrewhuszar** [comment]
Thanks guys for reporting. Unfortunatelly VSCode some API changes related to Code action executing and it seems tricky to make it work again. So for now it's cleaner to remove the Extract to File Code action.
