### ISSUE TITLE
How do I check the logs to see whats gone wrong?

### ISSUE THREAD

**Issue by max-carroll** [planbcoding/vscode-react-refactor#8]
I seem to be experiencing mixed results with this extension, most of the time it doesnt work. It seems to work on extracting small sections out of small components, but anything large it falls over. I will try and diagnose exactly whats going on, are there any logs or any output?

**Comment by palcisto** [comment]
I installed this extension today and have experienced the same issue. And for my use case, I'll define a large section as 55 lines in one instance and 25 lines (this is not large) in another instance. I use this wording because that's what @max-carroll uses and in my case I cannot think of what else the reason could be outside of considering the number of "dependencies" -- variables and functions -- that are necessary to be defined as props for the newly abstracted function.

I have a screen recording that I can share with the authors of the library if that will be helpful.

@andrewhussar any thoughts?

**Comment by andrewhuszar** [comment]
Hello, thanks for the feedback!

I just released an update that shows the error message coming from Babel parser.
Hope with this and that now the parser plugins are fully configurable you can find make it work!

If not, please open a new issue (check Readme)
